In [342]:
import pandapipes as pp
from tespy.components import Compressor,SimpleHeatExchanger,CycleCloser, Valve, HeatExchanger,Condenser, Sink, Source
from tespy.connections import Connection
from tespy.networks import Network
import numpy as np
from tespy.tools import UserDefinedEquation


class Bidirectional_W_to_WHeatPump:

    def __init__( self,name,net,refrigerant,HC_ext_id,HC_inj_id):
        self.name = name
        self.refrigerant = refrigerant
        self.HC_ext_id=HC_ext_id
        self.HC_inj_id=HC_inj_id
        self.net=net
        self._build_tespy_Cycles()

    def _build_tespy_Cycles(self):
        def my_ude(ude):
            dt_DHN=ude.params['dt']
            return ude.conns[0].calc_T()+dt_DHN-ude.conns[1].calc_T()
        def my_ude_dependents(ude):
            c1, c2 = ude.conns
            return [c1.p,c1.h, c2.p,c2.h]
        self.nw_Cooling_net = Network()
        self.nw_Cooling_net.units.set_defaults(temperature="degC", pressure="bar",pressure_difference="bar",  enthalpy="J/kg", heat="W", power="W")
        self.Cooling_net_compressor = Compressor("compresor")
        self.Cooling_net_condenser = Condenser("condensador")
        self.Cooling_net_valve = Valve("valvula_expansion")
        self.Cooling_net_evaporator = HeatExchanger("evaporador")
        self.Cooling_net_cc=CycleCloser('CycleCloser')
        self.Cooling_net_source_consumer=Source("Source_Consumer ")
        self.Cooling_net_sink_consumer=Sink("Sink_consumer")
        self.Cooling_net_source_reseau=Source("Source_Reseau")
        self.Cooling_net_sink_reseau=Sink("Sink_Reseau")
        self.Cooling_net_c0=Connection(self.Cooling_net_valve, 'out1', self.Cooling_net_cc, 'in1', label='0')
        self.Cooling_net_c1 = Connection(self.Cooling_net_cc, 'out1', self.Cooling_net_evaporator, 'in2', label='1')
        self.Cooling_net_c2 = Connection(self.Cooling_net_evaporator, 'out2', self.Cooling_net_compressor, 'in1', label='2')
        self.Cooling_net_c3 = Connection(self.Cooling_net_compressor, 'out1', self.Cooling_net_condenser, 'in1', label='3')
        self.Cooling_net_c4 = Connection(self.Cooling_net_condenser, 'out1', self.Cooling_net_valve, 'in1', label='4')
        self.Cooling_net_c5=Connection(self.Cooling_net_condenser, 'out2',self.Cooling_net_sink_consumer, 'in1', label='5')
        self.Cooling_net_c6=Connection(self.Cooling_net_source_consumer, 'out1',self.Cooling_net_condenser , 'in2', label='6')
        self.Cooling_net_c7=Connection(self.Cooling_net_source_reseau, 'out1',self.Cooling_net_evaporator , 'in1', label='7')
        self.Cooling_net_c8=Connection(self.Cooling_net_evaporator, 'out1',self.Cooling_net_sink_reseau , 'in1', label='8')
        self.nw_Cooling_net.add_conns(self.Cooling_net_c0,  self.Cooling_net_c1,  self.Cooling_net_c2,  self.Cooling_net_c3,  self.Cooling_net_c4 , self.Cooling_net_c5,  self.Cooling_net_c6, self.Cooling_net_c7, self.Cooling_net_c8)
        self.Cooling_ude = UserDefinedEquation(
                    'my_ude', my_ude, my_ude_dependents, conns=[self.Cooling_net_c8, self.Cooling_net_c7],params={'dt': 5})
        self.nw_Cooling_net.add_ude(self.Cooling_ude)
        
        #Heating net 
        self.nw_Heating_net = Network()
        self.nw_Heating_net.units.set_defaults(temperature="degC", pressure="bar",pressure_difference="bar",  enthalpy="J/kg", heat="W", power="W")
        self.Heating_net_compressor = Compressor("compresor")
        self.Heating_net_condenser = Condenser("condensador")
        self.Heating_net_valve = Valve("valvula_expansion")
        self.Heating_net_evaporator = HeatExchanger("evaporador")
        self.Heating_net_cc=CycleCloser('CycleCloser')
        self.Heating_net_source_consumer=Source("Source_Consumer ")
        self.Heating_net_sink_consumer=Sink("Sink_consumer")
        self.Heating_net_source_reseau=Source("Source_Reseau")
        self.Heating_net_sink_reseau=Sink("Sink_Reseau")
        self.Heating_net_c0=Connection(self.Heating_net_valve, 'out1', self.Heating_net_cc, 'in1', label='0')
        self.Heating_net_c1 = Connection(self.Heating_net_cc, 'out1', self.Heating_net_evaporator, 'in2', label='1')
        self.Heating_net_c2 = Connection(self.Heating_net_evaporator, 'out2', self.Heating_net_compressor, 'in1', label='2')
        self.Heating_net_c3 = Connection(self.Heating_net_compressor, 'out1', self.Heating_net_condenser, 'in1', label='3')
        self.Heating_net_c4 = Connection(self.Heating_net_condenser, 'out1', self.Heating_net_valve, 'in1', label='4')
        self.Heating_net_c5 = Connection(self.Heating_net_evaporator, 'out1', self.Heating_net_sink_consumer, 'in1', label='5')
        self.Heating_net_c6 = Connection(self.Heating_net_source_consumer, 'out1', self.Heating_net_evaporator, 'in1', label='6')  
        self.Heating_net_c7 = Connection(self.Heating_net_source_reseau, 'out1', self.Heating_net_condenser, 'in2', label='7')
        self.Heating_net_c8 = Connection(self.Heating_net_condenser, 'out2', self.Heating_net_sink_reseau, 'in1', label='8')
        self.nw_Heating_net.add_conns(self.Heating_net_c0,  self.Heating_net_c1,  self.Heating_net_c2,  self.Heating_net_c3,  self.Heating_net_c4 , self.Heating_net_c5,  self.Heating_net_c6, self.Heating_net_c7, self.Heating_net_c8)
        self.Heating_ude = UserDefinedEquation(
                        'my_ude_4', my_ude, my_ude_dependents, conns=[self.Heating_net_c7, self.Heating_net_c8],params={'dt': 5})
        self.nw_Heating_net.add_ude(self.Heating_ude)
        
    def solve_cycle(self,mode,Q_consumer,eta_s,T_nework_in,T_cons,dt_DHN):
        #The pressure values for the consumer and district heating side in the heating pump are arbitrary values
        self.mode=mode
        T_cons_in = T_cons[0]
        T_cons_out = T_cons[1]
        T_DH_in = T_nework_in
        if self.mode=="COOLING_NET":
            self.Cooling_net_evaporator.set_attr(pr1=1, pr2=1, ttd_l=5)
            self.Cooling_net_condenser.set_attr(pr1=1, pr2=1, ttd_u=5,Q=Q_consumer)
            self.Cooling_net_compressor.set_attr(eta_s=eta_s)
            self.Cooling_net_c2.set_attr(fluid={self.refrigerant: 1},td_dew=5)
            # 6. Parámetros del Consumidor 
            self.Cooling_net_c5.set_attr(T=T_cons_out, p=3, fluid={"water": 1})
            self.Cooling_net_c6.set_attr(T=T_cons_in)
            # 7. Parámetros de la Red de Distrito (Recibe calor, se calienta de 50 °C a 60 °C)
            self.Cooling_net_c7.set_attr(T=T_DH_in, p=2.5, fluid={"water": 1})
            import CoolProp.CoolProp as CP
            T_triple = CP.Props1SI("Ttriple", self.refrigerant)        # Triple point temperature (K)
            p_triple = CP.Props1SI("ptriple", self.refrigerant)        # Triple point pressure (Pa)
            T_critical = CP.Props1SI("T_critical", self.refrigerant)  # Critical temperature (K)
            p_critical = CP.Props1SI("p_critical", self.refrigerant)  # Critical pressure (Pa)
            h_min = CP.PropsSI("H", "T", T_triple + 0.1, "Q", 0, self.refrigerant)
            T_max_K =  T_critical*0.9
            p_high = min(p_critical * 0.9, 30e5) 
            h_max = CP.PropsSI("H", "T", T_max_K, "P", p_high, self.refrigerant)
            self.nw_Cooling_net._set_p_range([p_triple, p_high])
            self.nw_Cooling_net._set_h_range([h_min,h_max])
            self.Cooling_ude.params['dt'] = dt_DHN
            self.nw_Cooling_net.solve('design')        
        elif self.mode=="HEATING_NET":
            self.Heating_net_evaporator.set_attr(pr1=1, pr2=1, ttd_l=5,Q=Q_consumer)
            self.Heating_net_condenser.set_attr(pr1=1, pr2=1, ttd_u=5)
            self.Heating_net_compressor.set_attr(eta_s=eta_s)
            self.Heating_net_c2.set_attr(fluid={self.refrigerant: 1},td_dew=5)
            # 6. Parámetros del Consumidor 
            self.Heating_net_c5.set_attr(T=T_cons_out, p=3, fluid={"water": 1})
            self.Heating_net_c6.set_attr(T=T_cons_in)
            # 7. Parámetros de la Red de Distrito (Recibe calor, se calienta de 50 °C a 60 °C)
            self.Heating_net_c7.set_attr(T=T_DH_in, p=2.5, fluid={"water": 1})
            import CoolProp.CoolProp as CP
            T_triple = CP.Props1SI("Ttriple", self.refrigerant)        # Triple point temperature (K)
            p_triple = CP.Props1SI("ptriple", self.refrigerant)        # Triple point pressure (Pa)
            T_critical = CP.Props1SI("T_critical", self.refrigerant)  # Critical temperature (K)
            p_critical = CP.Props1SI("p_critical", self.refrigerant)  # Critical pressure (Pa)
            h_min = CP.PropsSI("H", "T", T_triple + 0.1, "Q", 0, self.refrigerant)
            T_max_K =  T_critical*0.9
            p_high = min(p_critical * 0.9, 30e5) 
            h_max = CP.PropsSI("H", "T", T_max_K, "P", p_high, self.refrigerant)
            self.nw_Heating_net._set_p_range([p_triple, p_high])
            self.nw_Heating_net._set_h_range([h_min,h_max])
            self.Heating_ude.params['dt'] = dt_DHN
            self.nw_Heating_net.solve('design')
    def interaction_simulation(self,dT_water):
        if self.mode=="COOLING_NET":
            self.net.heat_consumer.at[self.HC_ext_id, "qext_w"] =abs( self.Cooling_net_evaporator.Q.val)
            self.net.heat_consumer.at[self.HC_ext_id,"deltat_k"]=dT_water
            self.net.heat_consumer.at[self.HC_inj_id, "in_service"] =False
            
        elif self.mode=="HEATING_NET":
            self.net.heat_consumer.at[self.HC_inj_id, "qext_w"] = self.Heating_net_condenser.Q.val
            self.net.heat_consumer.at[self.HC_inj_id,"deltat_k"]=dT_water
            self.net.heat_consumer.at[self.HC_ext_id, "in_service"] =False

        else: 
            self.net.heat_consumer.at[self.HC_ext_id, "in_service"] =False
            self.net.heat_consumer.at[self.HC_inj_id, "in_service"] =False

    def get_main_results(self):
        if self.mode=="COOLING_NET":
            results = {
                "Q_consumer": abs(self.Cooling_net_condenser.Q.val),
                "Q_network": abs(self.Cooling_net_evaporator.Q.val),
                "W_compressor":self.Cooling_net_compressor.P.val ,
                "COP": abs(self.Cooling_net_condenser.Q.val)/self.Cooling_net_compressor.P.val 
            }
        elif self.mode=="HEATING_NET":
            results = {
                "Q_consumer": abs(self.Heating_net_evaporator.Q.val),
                "Q_network": abs(self.Heating_net_condenser.Q.val),
                "COP": abs(self.Heating_net_evaporator.Q.val)/self.Heating_net_compressor.P.val 
            }
        else:
            results = {}
        return results

    def get_results_solver(self):
        if self.mode=="COOLING_NET":
            self.nw_Cooling_net.print_results()
        elif self.mode=="HEATING_NET":
            self.nw_Heating_net.print_results()
        else:
            return None

In [343]:
import numpy as np
from pandapipes.component_models.abstract_models.circulation_pump import CirculationPump
from pandapipes.idx_branch import D, AREA, TOUTINIT
from pandapipes.idx_node import TINIT
from pandapipes.pf.pipeflow_setup import get_lookup

def _create_pit_branch_entries_fixed(cls, net, branch_pit):
    node_pit = net["_pit"]["node"]
    junction_idx_lookups = get_lookup(net, "node", "index")[
        cls.get_connected_node_type().table_name()]

    # FIX: usar la tabla COMPLETA, sin filtrar por in_service,
    # para que coincida con el tamaño de circ_pump_pit (que sí incluye
    # todas las filas, activas o no).
    circ_pump_tbl = net[cls.table_name()]
    circ_pump_pit = super(CirculationPump, cls).create_pit_branch_entries(net, branch_pit)
    circ_pump_pit[:, D] = 0.1
    circ_pump_pit[:, AREA] = circ_pump_pit[:, D] ** 2 * np.pi / 4

    types = circ_pump_tbl.type.values
    mask_t = np.isin(types, ["pt", "t"])
    juncts = circ_pump_tbl[cls.from_to_node_cols()[1]].values
    to_nodes = junction_idx_lookups[juncts]
    circ_pump_pit[mask_t, TOUTINIT] = circ_pump_tbl.t_flow_k.values[mask_t]
    circ_pump_pit[~mask_t, TOUTINIT] = node_pit[to_nodes[~mask_t], TINIT]
    return circ_pump_pit

CirculationPump.create_pit_branch_entries = classmethod(_create_pit_branch_entries_fixed)

In [344]:
net = pp.create_empty_network(fluid="water")
# Nudos de la Central / Fuente
j_fuente_ida = pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Fuente_Ida")
j_fuente_inter_normal=pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Fuente_Ida")
j_nodo_1 = pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="nodo_1_ida")
j_nodo_2=pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="nodo_2_ida") 
j_HP_1 = pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="HP_1_Ida")
j_HP_2 = pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="HP_2_Ida")
#Return
j_fuente_ret = pp.create_junction(net, pn_bar=1.5, tfluid_k=333.15, name="Fuente_Retorno")
j_fuente_inter_retro=pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Fuente_retro")
j_nodo_1_ret = pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Node_1_ret")
j_nodo_2_ret=pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Nodo_2_ret") 
j_HP_ret_1= pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="HP_1_ret")
j_HP_ret_2=pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="HP_2_ret")

#Plant-Nodo
u=0.35 / (np.pi * 0.15)
#Planta 1
pipe_ida_1 = pp.create_pipe_from_parameters(
    net, from_junction=j_fuente_ida, to_junction=j_nodo_1,
    length_km=0.0589, inner_diameter_mm=150, u_w_per_m2k=u, text_k=273.2, name="Tubo_Ida_Plant_Nodo_1",k_mm=0.1*1000
)

pipe_retorno_1= pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_1_ret, to_junction=j_fuente_ret,
    length_km=0.0589, inner_diameter_mm=150, u_w_per_m2k=u,  text_k=273.2, name="Tubo_RetornoPlant_Nodo_1",k_mm=0.1*1000)

#Nodo-nodo
pipe_ida_2 = pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_1, to_junction=j_nodo_2,
    length_km=0.0589, inner_diameter_mm=150, u_w_per_m2k=u,  text_k=273.2, name="nodo_1_nodo_2",k_mm=0.1*1000
)
pipe_retorno_2= pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_2_ret, to_junction=j_nodo_1_ret,
    length_km=0.0589, inner_diameter_mm=150, u_w_per_m2k=u,  text_k=273.2, name="nodo_2_ret_nodo_1_ret",k_mm=0.1*1000
)

#Node HP
#Node_Cons1

pipe_ida_3= pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_2, to_junction=j_HP_1,
    length_km=0.0376, inner_diameter_mm=150, u_w_per_m2k=u,  text_k=273.2, name="Tubo_Ida_nodo_2_cons_1_ida",k_mm=0.1*1000
)
pipe_retorno_3= pp.create_pipe_from_parameters(
    net, from_junction=j_HP_ret_1, to_junction=j_nodo_2_ret,
    length_km=0.0376, inner_diameter_mm=150, u_w_per_m2k=u,  text_k=273.2, name="Tubo_Retorno_nodo_2_cons_1_ret",k_mm=0.1*1000
)
#Node_Cons2
pipe_ida_4 = pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_2, to_junction=j_HP_2,
    length_km=0.0302, inner_diameter_mm=150, u_w_per_m2k=u,  text_k=273.2, name="Tubo_Ida_nodo_2_cons_2_ida",k_mm=0.1*1000
)
pipe_retorno_4= pp.create_pipe_from_parameters(
    net, from_junction=j_HP_ret_2, to_junction=j_nodo_2_ret,
    length_km=0.0302, inner_diameter_mm=150, u_w_per_m2k=u,  text_k=273.2, name="Tubo_Retorno_nodo_2_cons_2_ret",k_mm=0.1*1000
)

#Heat Pumps
#Heat pump: extraction
HP_1_Ext=pp.create_heat_consumer(
    net,
    from_junction=j_HP_1 ,
    to_junction=j_HP_ret_1,
    qext_w=150000,
    deltat_k=50,
    name="HP_1_EXT"
)
#Heat mump 1: Injection
HP_1_inj=pp.create_heat_consumer(
    net,
    from_junction=j_HP_ret_1,
    to_junction=j_HP_1,
    qext_w=-150000,
    deltat_k=50,
    name="HP_1_INJ"
)
#Heat pump: extraction
HP_2_Ext=pp.create_heat_consumer(
    net,
    from_junction=j_HP_2 ,
    to_junction=j_HP_ret_2,
    qext_w=150000,
    deltat_k=50,
    name="HP_2_EXT"
)
#Heat mump 1: Injection
HP_2_inj=pp.create_heat_consumer(
    net,
    from_junction=j_HP_ret_2,
    to_junction=j_HP_2,
    qext_w=150000,
    deltat_k=-50,
    name="HP_2_INJ"
)
#Plant: 
Plant_1_normal=pp.create_circ_pump_const_pressure(net,flow_junction=j_fuente_ida,return_junction=j_fuente_ret,p_flow_bar=3,plift_bar=0.5,t_flow_k=340)
Plant_1_ret=pp.create_circ_pump_const_pressure(net,flow_junction=j_fuente_ret,return_junction=j_fuente_ida,p_flow_bar=2.5,plift_bar=-0.5,t_flow_k=305)

T_network_inital_guess_1=35
T_network_inital_guess_2=50

In [345]:
HP_1=Bidirectional_W_to_WHeatPump(name="heat_pump_1",refrigerant="R134a",net=net,HC_ext_id=HP_1_Ext,HC_inj_id=HP_1_inj)
HP_2=Bidirectional_W_to_WHeatPump(name="heat_pump_2",refrigerant="R134a",net=net,HC_ext_id=HP_2_Ext,HC_inj_id=HP_2_inj)
T_network_HP_1=T_network_inital_guess_1
T_network_HP_2=T_network_inital_guess_2
T_network_HP_1_loop=T_network_inital_guess_1
T_network_HP_2_loop=T_network_inital_guess_2
tolerance=1E-6
error_1=10
error_2=10
iterations=0
while error_1>tolerance or error_2>tolerance:
    HP_1.solve_cycle(mode="COOLING_NET",Q_consumer=-150,eta_s=0.95,T_nework_in=T_network_HP_1,T_cons=[50,60],dt_DHN=5)
    HP_2.solve_cycle(mode="HEATING_NET",Q_consumer=-150000,eta_s=0.95,T_nework_in=T_network_HP_2,T_cons=[35,25],dt_DHN=10)
    print("iteration")
    HP_1.interaction_simulation(dT_water=5)
    HP_2.interaction_simulation(dT_water=-10)
    try:
        net.circ_pump_pressure.at[Plant_1_normal, "in_service"] = True
        net.circ_pump_pressure.at[Plant_1_ret, "in_service"] = False
        pp.pipeflow(net, mode="bidirectional")
    except UserWarning as e:
        print("modo directo falla:", e)
        net.circ_pump_pressure.at[Plant_1_normal, "in_service"] = False
        net.circ_pump_pressure.at[Plant_1_ret, "in_service"] = True
        pp.pipeflow(net, mode="bidirectional")
    T_network_HP_1=float(net.res_heat_consumer.at[HP_1.HC_ext_id,"t_from_k"]-273.15)
    T_network_HP_2=float(net.res_heat_consumer.at[HP_2.HC_inj_id,"t_from_k"]-273.15)
    error_1=abs(T_network_HP_1_loop-T_network_HP_1)
    error_2=abs(T_network_HP_2_loop-T_network_HP_2)
    print(error_1)
    print(error_2)
    T_network_HP_1_loop=T_network_HP_1
    T_network_HP_2_loop=T_network_HP_2
    iterations+=1

 iter  | residual   | progress   | massflow   | pressure   | enthalpy   | fluid      | energy     | component
-------+------------+------------+------------+------------+------------+------------+------------+------------
 1     | 9.08e+05   | 0 %        | 2.02e+00   | 1.42e+06   | 4.03e+05   | 0.00e+00   | 0.00e+00   | 0.00e+00
 2     | 4.56e+04   | 14 %       | 1.49e+00   | 1.97e+05   | 6.96e+03   | 0.00e+00   | 0.00e+00   | 0.00e+00
 3     | 7.04e+03   | 23 %       | 3.38e-01   | 1.64e+04   | 4.58e+02   | 0.00e+00   | 0.00e+00   | 0.00e+00
 4     | 1.73e+00   | 64 %       | 2.56e-06   | 1.58e+02   | 4.33e+00   | 0.00e+00   | 0.00e+00   | 0.00e+00
 5     | 1.70e-04   | 100 %      | 2.62e-12   | 1.41e-02   | 3.71e-04   | 0.00e+00   | 0.00e+00   | 0.00e+00
 6     | 3.45e-10   | 100 %      | 5.48e-15   | 4.94e-09   | 1.90e-08   | 0.00e+00   | 0.00e+00   | 0.00e+00
Total iterations: 6, Calculation time: 0.03 s, Iterations per second: 226.91

 iter  | residual   | progress   | massflow   | pressure   | enthalpy   | fluid      | energy     | component
-------+------------+------------+------------+------------+------------+------------+------------+------------
 1     | 4.52e+06   | 0 %        | 2.79e+00   | 1.61e+06   | 3.83e+05   | 0.00e+00   | 0.00e+00   | 0.00e+00
 2     | 5.44e+05   | 2 %        | 1.15e+00   | 2.95e+06   | 2.07e+06   | 0.00e+00   | 0.00e+00   | 0.00e+00
 3     | 1.92e+05   | 7 %        | 1.31e+02   | 5.76e+06   | 3.61e+05   | 0.00e+00   | 0.00e+00   | 0.00e+00
 4     | 3.90e+07   | 0 %        | 1.28e+03   | 2.11e+08   | 2.01e+06   | 0.00e+00   | 0.00e+00   | 0.00e+00
 5     | 4.43e+08   | 0 %        | 9.88e+04   | 2.17e+08   | 1.67e+06   | 0.00e+00   | 0.00e+00   | 0.00e+00
 6     | 1.00e+09   | 0 %        | 1.54e+05   | 4.04e+05   | 3.85e+05   | 0.00e+00   | 0.00e+00   | 0.00e+00
 7     | 2.42e+09   | 0 %        | 5.64e+04   | 5.97e+04   | 2.09e+03   | 0.00e+00   | 0.00e+00   | 0.00e+00
 8     | 8.87e+05   | 0 %        | 2.57e+01   | 2.70e+03   | 8.72e+01   | 0.00e+00   | 0.00e+00   | 0.00e+00
 9     | 6.50e+02   | 35 %       | 1.60e-02   | 4.85e+00   | 1.55e-01   | 0.00e+00   | 0.00e+00   | 0.00e+00
 10    | 8.17e-04   | 100 %      | 2.08e-08   | 1.56e-05   | 8.59e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
 11    | 2.61e-10   | 100 %      | 1.07e-12   | 1.00e-09   | 1.02e-08   | 0.00e+00   | 0.00e+00   | 0.00e+00
Total iterations: 11, Calculation time: 0.06 s, Iterations per second: 177.52
iteration
modo directo falla: Your grid is badly modelled and would lead to a direction change in circulation pump [0]
10.24011801280318
18.267219194168717

 iter  | residual   | progress   | massflow   | pressure   | enthalpy   | fluid      | energy     | component
-------+------------+------------+------------+------------+------------+------------+------------+------------
 1     | 2.58e+02   | 39 %       | 3.17e-04   | 2.03e+05   | 4.32e+04   | 0.00e+00   | 0.00e+00   | 0.00e+00
 2     | 3.50e+02   | 38 %       | 6.65e-04   | 2.18e+04   | 8.41e+02   | 0.00e+00   | 0.00e+00   | 0.00e+00
 3     | 7.34e+00   | 57 %       | 2.62e-07   | 3.94e+02   | 1.49e+01   | 0.00e+00   | 0.00e+00   | 0.00e+00
 4     | 2.22e-03   | 96 %       | 9.75e-11   | 1.22e-01   | 4.58e-03   | 0.00e+00   | 0.00e+00   | 0.00e+00
 5     | 5.07e-06   | 100 %      | 3.12e-15   | 1.15e-08   | 4.46e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
 6     | 3.13e-10   | 100 %      | 3.74e-15   | 0.00e+00   | 1.38e-08   | 0.00e+00   | 0.00e+00   | 0.00e+00
Total iterations: 6, Calculation time: 0.03 s, Iterations per second: 234.42

 iter  | residual   | progress   | massflow   | pressure   | enthalpy   | fluid      | energy     | component
-------+------------+------------+------------+------------+------------+------------+------------+------------
 1     | 3.35e+05   | 5 %        | 3.65e-01   | 7.94e+05   | 8.28e+04   | 0.00e+00   | 0.00e+00   | 0.00e+00
 2     | 2.27e+04   | 18 %       | 2.35e-01   | 1.13e+05   | 1.54e+03   | 0.00e+00   | 0.00e+00   | 0.00e+00
 3     | 2.69e+02   | 39 %       | 1.57e-03   | 4.41e+03   | 5.44e+01   | 0.00e+00   | 0.00e+00   | 0.00e+00
 4     | 2.91e-01   | 72 %       | 1.68e-06   | 6.05e+00   | 7.47e-02   | 0.00e+00   | 0.00e+00   | 0.00e+00
 5     | 1.24e-05   | 100 %      | 2.28e-12   | 1.15e-05   | 8.67e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
 6     | 1.13e-09   | 100 %      | 2.32e-10   | 4.00e-05   | 3.40e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
Total iterations: 6, Calculation time: 0.02 s, Iterations per second: 259.66
iteration
modo directo falla: Your grid is badly modelled and would lead to a direction change in circulation pump [0]
0.7750855323932342
0.0109733621895316

 iter  | residual   | progress   | massflow   | pressure   | enthalpy   | fluid      | energy     | component
-------+------------+------------+------------+------------+------------+------------+------------+------------
 1     | 1.84e+01   | 52 %       | 3.22e-05   | 1.21e+04   | 3.28e+03   | 0.00e+00   | 0.00e+00   | 0.00e+00
 2     | 2.13e+00   | 63 %       | 4.88e-06   | 1.14e+02   | 4.38e+00   | 0.00e+00   | 0.00e+00   | 0.00e+00
 3     | 2.01e-04   | 100 %      | 5.90e-11   | 1.05e-02   | 3.98e-04   | 0.00e+00   | 0.00e+00   | 0.00e+00
 4     | 4.89e-10   | 100 %      | 7.20e-15   | 8.70e-10   | 2.66e-08   | 0.00e+00   | 0.00e+00   | 0.00e+00
Total iterations: 4, Calculation time: 0.02 s, Iterations per second: 228.58

 iter  | residual   | progress   | massflow   | pressure   | enthalpy   | fluid      | energy     | component
-------+------------+------------+------------+------------+------------+------------+------------+------------
 1     | 1.83e+02   | 41 %       | 2.29e-04   | 3.42e+02   | 4.92e+01   | 0.00e+00   | 0.00e+00   | 0.00e+00
 2     | 1.06e-02   | 88 %       | 2.01e-07   | 3.60e-02   | 4.45e-04   | 0.00e+00   | 0.00e+00   | 0.00e+00
 3     | 9.99e-10   | 100 %      | 1.30e-11   | 2.00e-05   | 1.05e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
 4     | 7.66e-10   | 100 %      | 1.32e-11   | 2.00e-05   | 1.05e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
Total iterations: 4, Calculation time: 0.01 s, Iterations per second: 283.62
iteration
modo directo falla: Your grid is badly modelled and would lead to a direction change in circulation pump [0]
0.06265312294584646
4.266348832970834e-05

 iter  | residual   | progress   | massflow   | pressure   | enthalpy   | fluid      | energy     | component
-------+------------+------------+------------+------------+------------+------------+------------+------------
 1     | 1.48e+00   | 64 %       | 2.25e-06   | 9.59e+02   | 2.65e+02   | 0.00e+00   | 0.00e+00   | 0.00e+00
 2     | 1.40e-02   | 87 %       | 2.74e-08   | 7.39e-01   | 2.85e-02   | 0.00e+00   | 0.00e+00   | 0.00e+00
 3     | 4.58e-06   | 100 %      | 2.25e-14   | 1.70e-07   | 4.00e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
 4     | 6.16e-10   | 100 %      | 1.71e-15   | 2.71e-07   | 1.36e-08   | 0.00e+00   | 0.00e+00   | 0.00e+00
Total iterations: 4, Calculation time: 0.01 s, Iterations per second: 276.66

 iter  | residual   | progress   | massflow   | pressure   | enthalpy   | fluid      | energy     | component
-------+------------+------------+------------+------------+------------+------------+------------+------------
 1     | 7.13e-01   | 68 %       | 8.90e-07   | 1.33e+00   | 1.91e-01   | 0.00e+00   | 0.00e+00   | 0.00e+00
 2     | 1.26e-05   | 100 %      | 2.59e-10   | 5.47e-07   | 9.08e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
 3     | 3.36e-10   | 100 %      | 3.23e-12   | 0.00e+00   | 3.37e-08   | 0.00e+00   | 0.00e+00   | 0.00e+00
 4     | 1.08e-09   | 100 %      | 2.58e-10   | 0.00e+00   | 2.70e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
Total iterations: 4, Calculation time: 0.02 s, Iterations per second: 259.72
iteration
modo directo falla: Your grid is badly modelled and would lead to a direction change in circulation pump [0]
0.005094106559454303
4.017812557322031e-06

 iter  | residual   | progress   | massflow   | pressure   | enthalpy   | fluid      | energy     | component
-------+------------+------------+------------+------------+------------+------------+------------+------------
 1     | 1.21e-01   | 76 %       | 1.81e-07   | 7.78e+01   | 2.15e+01   | 0.00e+00   | 0.00e+00   | 0.00e+00
 2     | 9.72e-05   | 100 %      | 1.79e-10   | 4.88e-03   | 1.84e-04   | 0.00e+00   | 0.00e+00   | 0.00e+00
 3     | 4.90e-10   | 100 %      | 1.42e-14   | 2.47e-09   | 5.26e-08   | 0.00e+00   | 0.00e+00   | 0.00e+00
 4     | 3.16e-10   | 100 %      | 1.97e-14   | 0.00e+00   | 7.28e-08   | 0.00e+00   | 0.00e+00   | 0.00e+00
Total iterations: 4, Calculation time: 0.02 s, Iterations per second: 248.78

 iter  | residual   | progress   | massflow   | pressure   | enthalpy   | fluid      | energy     | component
-------+------------+------------+------------+------------+------------+------------+------------+------------
 1     | 6.71e-02   | 79 %       | 8.37e-08   | 1.25e-01   | 1.80e-02   | 0.00e+00   | 0.00e+00   | 0.00e+00
 2     | 1.26e-05   | 100 %      | 2.55e-10   | 5.66e-08   | 9.07e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
 3     | 1.04e-09   | 100 %      | 2.53e-10   | 4.60e-08   | 2.65e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
 4     | 9.50e-10   | 100 %      | 2.55e-10   | 1.11e-07   | 2.67e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
Total iterations: 4, Calculation time: 0.02 s, Iterations per second: 250.35
iteration
modo directo falla: Your grid is badly modelled and would lead to a direction change in circulation pump [0]
0.000414381841778777
3.271965738349536e-07

 iter  | residual   | progress   | massflow   | pressure   | enthalpy   | fluid      | energy     | component
-------+------------+------------+------------+------------+------------+------------+------------+------------
 1     | 9.81e-03   | 88 %       | 1.47e-08   | 6.33e+00   | 1.75e+00   | 0.00e+00   | 0.00e+00   | 0.00e+00
 2     | 5.20e-06   | 100 %      | 1.19e-12   | 3.25e-05   | 2.80e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
 3     | 5.12e-10   | 100 %      | 2.24e-14   | 2.47e-09   | 8.30e-08   | 0.00e+00   | 0.00e+00   | 0.00e+00
 4     | 3.16e-10   | 100 %      | 3.14e-14   | 2.22e-16   | 1.16e-07   | 0.00e+00   | 0.00e+00   | 0.00e+00
Total iterations: 4, Calculation time: 0.02 s, Iterations per second: 238.89

 iter  | residual   | progress   | massflow   | pressure   | enthalpy   | fluid      | energy     | component
-------+------------+------------+------------+------------+------------+------------+------------+------------
 1     | 5.47e-03   | 91 %       | 6.72e-09   | 1.02e-02   | 1.47e-03   | 0.00e+00   | 0.00e+00   | 0.00e+00
 2     | 7.21e-10   | 100 %      | 1.15e-11   | 2.01e-05   | 1.06e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
 3     | 9.43e-10   | 100 %      | 2.52e-10   | 0.00e+00   | 2.64e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
 4     | 4.92e-10   | 100 %      | 2.86e-12   | 0.00e+00   | 2.99e-08   | 0.00e+00   | 0.00e+00   | 0.00e+00
Total iterations: 4, Calculation time: 0.02 s, Iterations per second: 247.17
iteration
modo directo falla: Your grid is badly modelled and would lead to a direction change in circulation pump [0]
3.3709346325849765e-05
2.6617613002599683e-08

 iter  | residual   | progress   | massflow   | pressure   | enthalpy   | fluid      | energy     | component
-------+------------+------------+------------+------------+------------+------------+------------+------------
 1     | 7.98e-04   | 100 %      | 1.19e-09   | 5.15e-01   | 1.42e-01   | 0.00e+00   | 0.00e+00   | 0.00e+00
 2     | 4.57e-06   | 100 %      | 1.83e-14   | 2.13e-07   | 4.00e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
 3     | 4.92e-10   | 100 %      | 7.78e-16   | 2.62e-09   | 2.89e-09   | 0.00e+00   | 0.00e+00   | 0.00e+00
 4     | 4.57e-10   | 100 %      | 3.48e-14   | 9.66e-23   | 1.29e-07   | 0.00e+00   | 0.00e+00   | 0.00e+00
Total iterations: 4, Calculation time: 0.02 s, Iterations per second: 227.47

 iter  | residual   | progress   | massflow   | pressure   | enthalpy   | fluid      | energy     | component
-------+------------+------------+------------+------------+------------+------------+------------+------------
 1     | 4.45e-04   | 100 %      | 6.62e-10   | 8.19e-04   | 1.18e-04   | 0.00e+00   | 0.00e+00   | 0.00e+00
 2     | 9.84e-10   | 100 %      | 2.55e-10   | 1.77e-09   | 2.67e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
 3     | 3.00e-10   | 100 %      | 1.58e-12   | 5.31e-09   | 1.66e-08   | 0.00e+00   | 0.00e+00   | 0.00e+00
 4     | 1.06e-09   | 100 %      | 2.54e-10   | 7.08e-09   | 2.66e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
Total iterations: 4, Calculation time: 0.01 s, Iterations per second: 268.59
iteration
modo directo falla: Your grid is badly modelled and would lead to a direction change in circulation pump [0]
2.7422123025644396e-06
2.1651089809893165e-09

 iter  | residual   | progress   | massflow   | pressure   | enthalpy   | fluid      | energy     | component
-------+------------+------------+------------+------------+------------+------------+------------+------------
 1     | 6.49e-05   | 100 %      | 9.71e-11   | 4.19e-02   | 1.16e-02   | 0.00e+00   | 0.00e+00   | 0.00e+00
 2     | 2.97e-10   | 100 %      | 1.88e-14   | 5.02e-09   | 6.95e-08   | 0.00e+00   | 0.00e+00   | 0.00e+00
 3     | 4.66e-10   | 100 %      | 1.61e-14   | 2.47e-09   | 5.95e-08   | 0.00e+00   | 0.00e+00   | 0.00e+00
 4     | 2.96e-10   | 100 %      | 4.13e-14   | 6.16e-16   | 1.53e-07   | 0.00e+00   | 0.00e+00   | 0.00e+00
Total iterations: 4, Calculation time: 0.01 s, Iterations per second: 267.99

 iter  | residual   | progress   | massflow   | pressure   | enthalpy   | fluid      | energy     | component
-------+------------+------------+------------+------------+------------+------------+------------+------------
 1     | 3.63e-05   | 100 %      | 3.90e-11   | 6.80e-05   | 9.83e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
 2     | 2.81e-10   | 100 %      | 2.28e-12   | 6.73e-17   | 2.38e-08   | 0.00e+00   | 0.00e+00   | 0.00e+00
 3     | 1.15e-09   | 100 %      | 2.60e-10   | 1.56e-12   | 2.72e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
 4     | 6.94e-10   | 100 %      | 1.22e-12   | 0.00e+00   | 1.28e-08   | 0.00e+00   | 0.00e+00   | 0.00e+00
Total iterations: 4, Calculation time: 0.01 s, Iterations per second: 268.09
iteration
modo directo falla: Your grid is badly modelled and would lead to a direction change in circulation pump [0]
2.230733571195742e-07
1.7621459846850485e-10

In [346]:
net.pipe

,name,from_junction,to_junction,std_type,length_km,inner_diameter_mm,outer_diameter_mm,k_mm,loss_coefficient,u_w_per_m2k,text_k,sections,in_service,type
0,Tubo_Ida_Plant_Nodo_1,0,2,None,0.0589,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
1,Tubo_RetornoPlant_Nodo_1,8,6,None,0.0589,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
2,nodo_1_nodo_2,2,3,None,0.0589,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
3,nodo_2_ret_nodo_1_ret,9,8,None,0.0589,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
4,Tubo_Ida_nodo_2_cons_1_ida,3,4,None,0.0376,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
5,Tubo_Retorno_nodo_2_cons_1_ret,10,9,None,0.0376,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
6,Tubo_Ida_nodo_2_cons_2_ida,3,5,None,0.0302,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe
7,Tubo_Retorno_nodo_2_cons_2_ret,11,9,None,0.0302,150.0,150.0,100.0,0.0,0.742723,273.2,1,True,pipe

In [347]:
net.res_pipe

,v_mean_m_per_s,p_from_bar,p_to_bar,t_from_k,t_to_k,t_outlet_k,mdot_from_kg_per_s,mdot_to_kg_per_s,vdot_m3_per_s,reynolds,lambda,dp_friction_loss_bar
0,-0.227743,3.000000,3.045543,314.742677,314.794053,314.742677,-3.990387,3.990387,-0.004025,53522.886442,0.451064,-4.554290e-02
1,-0.226943,2.454592,2.500000,304.960722,305.000000,304.960722,-3.990387,3.990387,-0.004010,44154.838411,0.451318,-4.540826e-02
2,-0.227748,3.045543,3.091087,314.794053,314.845492,314.794053,-3.990387,3.990387,-0.004025,53572.497890,0.451063,-4.554374e-02
3,-0.226940,2.409184,2.454592,304.891903,304.960722,304.921492,-3.990387,3.990387,-0.004010,44119.618922,0.451319,-4.540780e-02
4,0.000322,3.091087,3.091086,314.845492,297.066598,297.066598,0.005654,-0.005654,0.000006,63.827438,1.452572,1.874093e-07
5,0.000320,2.409184,2.409184,292.066598,304.891903,284.024991,0.005654,-0.005654,0.000006,42.217508,1.965827,2.524600e-07
6,-0.228074,3.091087,3.114505,314.845492,314.871854,314.845492,-3.996041,3.996041,-0.004030,53686.058236,0.451060,-2.341826e-02
7,-0.227257,2.385836,2.409184,304.871854,304.891903,304.871854,-3.996041,3.996041,-0.004016,44129.019944,0.451318,-2.334765e-02

In [348]:
net.heat_consumer

,name,from_junction,to_junction,qext_w,controlled_mdot_kg_per_s,deltat_k,treturn_k,in_service,type
0,HP_1_EXT,4,10,118.271242,NaN,5.0,NaN,True,heat_consumer
1,HP_1_INJ,10,4,-150000.000000,NaN,50.0,NaN,False,heat_consumer
2,HP_2_EXT,5,11,150000.000000,NaN,50.0,NaN,False,heat_consumer
3,HP_2_INJ,11,5,-167033.751951,NaN,-10.0,NaN,True,heat_consumer

In [349]:
net.res_heat_consumer

,p_from_bar,p_to_bar,t_from_k,t_to_k,t_outlet_k,mdot_from_kg_per_s,mdot_to_kg_per_s,vdot_m3_per_s,deltat_k,qext_w
0,3.091086,2.409184,297.066598,292.066598,292.066598,0.005654,-0.005654,0.000006,5.000000,118.271242
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.083402,-150000.000000
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.721854,150000.000000
3,2.385836,3.114505,304.871854,314.871854,314.871854,3.996041,-3.996041,0.004023,-10.000000,-167033.751951

In [350]:
net.res_circ_pump_pressure

,p_from_bar,p_to_bar,t_from_k,t_to_k,t_outlet_k,mdot_from_kg_per_s,mdot_to_kg_per_s,vdot_m3_per_s,deltat_k,qext_w
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.850000,NaN
1,3.0,2.5,314.742677,305.0,305.0,3.990387,-3.990387,0.004017,9.742677,-162504.736526

In [351]:
# Segundo es no fijando un circpump 
import pandapipes as pp
from tespy.components import Compressor,SimpleHeatExchanger,CycleCloser, Valve, HeatExchanger,Condenser, Sink, Source
from tespy.connections import Connection
from tespy.networks import Network
import numpy as np
from tespy.tools import UserDefinedEquation


class Bidirectional_W_to_WHeatPump:

    def __init__( self,name,net,refrigerant,HC_ext_id,HC_inj_id):
        self.name = name
        self.refrigerant = refrigerant
        self.HC_ext_id=HC_ext_id
        self.HC_inj_id=HC_inj_id
        self.net=net
        self._build_tespy_Cycles()

    def _build_tespy_Cycles(self):
        def my_ude(ude):
            dt_DHN=ude.params['dt']
            return ude.conns[0].calc_T()+dt_DHN-ude.conns[1].calc_T()
        def my_ude_dependents(ude):
            c1, c2 = ude.conns
            return [c1.p,c1.h, c2.p,c2.h]
        self.nw_Cooling_net = Network()
        self.nw_Cooling_net.units.set_defaults(temperature="degC", pressure="bar",pressure_difference="bar",  enthalpy="J/kg", heat="W", power="W")
        self.Cooling_net_compressor = Compressor("compresor")
        self.Cooling_net_condenser = Condenser("condensador")
        self.Cooling_net_valve = Valve("valvula_expansion")
        self.Cooling_net_evaporator = HeatExchanger("evaporador")
        self.Cooling_net_cc=CycleCloser('CycleCloser')
        self.Cooling_net_source_consumer=Source("Source_Consumer ")
        self.Cooling_net_sink_consumer=Sink("Sink_consumer")
        self.Cooling_net_source_reseau=Source("Source_Reseau")
        self.Cooling_net_sink_reseau=Sink("Sink_Reseau")
        self.Cooling_net_c0=Connection(self.Cooling_net_valve, 'out1', self.Cooling_net_cc, 'in1', label='0')
        self.Cooling_net_c1 = Connection(self.Cooling_net_cc, 'out1', self.Cooling_net_evaporator, 'in2', label='1')
        self.Cooling_net_c2 = Connection(self.Cooling_net_evaporator, 'out2', self.Cooling_net_compressor, 'in1', label='2')
        self.Cooling_net_c3 = Connection(self.Cooling_net_compressor, 'out1', self.Cooling_net_condenser, 'in1', label='3')
        self.Cooling_net_c4 = Connection(self.Cooling_net_condenser, 'out1', self.Cooling_net_valve, 'in1', label='4')
        self.Cooling_net_c5=Connection(self.Cooling_net_condenser, 'out2',self.Cooling_net_sink_consumer, 'in1', label='5')
        self.Cooling_net_c6=Connection(self.Cooling_net_source_consumer, 'out1',self.Cooling_net_condenser , 'in2', label='6')
        self.Cooling_net_c7=Connection(self.Cooling_net_source_reseau, 'out1',self.Cooling_net_evaporator , 'in1', label='7')
        self.Cooling_net_c8=Connection(self.Cooling_net_evaporator, 'out1',self.Cooling_net_sink_reseau , 'in1', label='8')
        self.nw_Cooling_net.add_conns(self.Cooling_net_c0,  self.Cooling_net_c1,  self.Cooling_net_c2,  self.Cooling_net_c3,  self.Cooling_net_c4 , self.Cooling_net_c5,  self.Cooling_net_c6, self.Cooling_net_c7, self.Cooling_net_c8)
        self.Cooling_ude = UserDefinedEquation(
                    'my_ude', my_ude, my_ude_dependents, conns=[self.Cooling_net_c8, self.Cooling_net_c7],params={'dt': 5})
        self.nw_Cooling_net.add_ude(self.Cooling_ude)
        
        #Heating net 
        self.nw_Heating_net = Network()
        self.nw_Heating_net.units.set_defaults(temperature="degC", pressure="bar",pressure_difference="bar",  enthalpy="J/kg", heat="W", power="W")
        self.Heating_net_compressor = Compressor("compresor")
        self.Heating_net_condenser = Condenser("condensador")
        self.Heating_net_valve = Valve("valvula_expansion")
        self.Heating_net_evaporator = HeatExchanger("evaporador")
        self.Heating_net_cc=CycleCloser('CycleCloser')
        self.Heating_net_source_consumer=Source("Source_Consumer ")
        self.Heating_net_sink_consumer=Sink("Sink_consumer")
        self.Heating_net_source_reseau=Source("Source_Reseau")
        self.Heating_net_sink_reseau=Sink("Sink_Reseau")
        self.Heating_net_c0=Connection(self.Heating_net_valve, 'out1', self.Heating_net_cc, 'in1', label='0')
        self.Heating_net_c1 = Connection(self.Heating_net_cc, 'out1', self.Heating_net_evaporator, 'in2', label='1')
        self.Heating_net_c2 = Connection(self.Heating_net_evaporator, 'out2', self.Heating_net_compressor, 'in1', label='2')
        self.Heating_net_c3 = Connection(self.Heating_net_compressor, 'out1', self.Heating_net_condenser, 'in1', label='3')
        self.Heating_net_c4 = Connection(self.Heating_net_condenser, 'out1', self.Heating_net_valve, 'in1', label='4')
        self.Heating_net_c5 = Connection(self.Heating_net_evaporator, 'out1', self.Heating_net_sink_consumer, 'in1', label='5')
        self.Heating_net_c6 = Connection(self.Heating_net_source_consumer, 'out1', self.Heating_net_evaporator, 'in1', label='6')  
        self.Heating_net_c7 = Connection(self.Heating_net_source_reseau, 'out1', self.Heating_net_condenser, 'in2', label='7')
        self.Heating_net_c8 = Connection(self.Heating_net_condenser, 'out2', self.Heating_net_sink_reseau, 'in1', label='8')
        self.nw_Heating_net.add_conns(self.Heating_net_c0,  self.Heating_net_c1,  self.Heating_net_c2,  self.Heating_net_c3,  self.Heating_net_c4 , self.Heating_net_c5,  self.Heating_net_c6, self.Heating_net_c7, self.Heating_net_c8)
        self.Heating_ude = UserDefinedEquation(
                        'my_ude_4', my_ude, my_ude_dependents, conns=[self.Heating_net_c7, self.Heating_net_c8],params={'dt': 5})
        self.nw_Heating_net.add_ude(self.Heating_ude)
        
    def solve_cycle(self,mode,Q_consumer,eta_s,T_nework_in,T_cons,dt_DHN):
        #The pressure values for the consumer and district heating side in the heating pump are arbitrary values
        self.mode=mode
        T_cons_in = T_cons[0]
        T_cons_out = T_cons[1]
        T_DH_in = T_nework_in
        if self.mode=="COOLING_NET":
            self.Cooling_net_evaporator.set_attr(pr1=1, pr2=1, ttd_l=5)
            self.Cooling_net_condenser.set_attr(pr1=1, pr2=1, ttd_u=5,Q=Q_consumer)
            self.Cooling_net_compressor.set_attr(eta_s=eta_s)
            self.Cooling_net_c2.set_attr(fluid={self.refrigerant: 1},td_dew=5)
            # 6. Parámetros del Consumidor 
            self.Cooling_net_c5.set_attr(T=T_cons_out, p=3, fluid={"water": 1})
            self.Cooling_net_c6.set_attr(T=T_cons_in)
            # 7. Parámetros de la Red de Distrito (Recibe calor, se calienta de 50 °C a 60 °C)
            self.Cooling_net_c7.set_attr(T=T_DH_in, p=2.5, fluid={"water": 1})
            import CoolProp.CoolProp as CP
            T_triple = CP.Props1SI("Ttriple", self.refrigerant)        # Triple point temperature (K)
            p_triple = CP.Props1SI("ptriple", self.refrigerant)        # Triple point pressure (Pa)
            T_critical = CP.Props1SI("T_critical", self.refrigerant)  # Critical temperature (K)
            p_critical = CP.Props1SI("p_critical", self.refrigerant)  # Critical pressure (Pa)
            h_min = CP.PropsSI("H", "T", T_triple + 0.1, "Q", 0, self.refrigerant)
            T_max_K =  T_critical*0.9
            p_high = min(p_critical * 0.9, 30e5) 
            h_max = CP.PropsSI("H", "T", T_max_K, "P", p_high, self.refrigerant)
            self.nw_Cooling_net._set_p_range([p_triple, p_high])
            self.nw_Cooling_net._set_h_range([h_min,h_max])
            self.Cooling_ude.params['dt'] = dt_DHN
            self.nw_Cooling_net.solve('design')        
        elif self.mode=="HEATING_NET":
            self.Heating_net_evaporator.set_attr(pr1=1, pr2=1, ttd_l=5,Q=Q_consumer)
            self.Heating_net_condenser.set_attr(pr1=1, pr2=1, ttd_u=5)
            self.Heating_net_compressor.set_attr(eta_s=eta_s)
            self.Heating_net_c2.set_attr(fluid={self.refrigerant: 1},td_dew=5)
            # 6. Parámetros del Consumidor 
            self.Heating_net_c5.set_attr(T=T_cons_out, p=3, fluid={"water": 1})
            self.Heating_net_c6.set_attr(T=T_cons_in)
            # 7. Parámetros de la Red de Distrito (Recibe calor, se calienta de 50 °C a 60 °C)
            self.Heating_net_c7.set_attr(T=T_DH_in, p=2.5, fluid={"water": 1})
            import CoolProp.CoolProp as CP
            T_triple = CP.Props1SI("Ttriple", self.refrigerant)        # Triple point temperature (K)
            p_triple = CP.Props1SI("ptriple", self.refrigerant)        # Triple point pressure (Pa)
            T_critical = CP.Props1SI("T_critical", self.refrigerant)  # Critical temperature (K)
            p_critical = CP.Props1SI("p_critical", self.refrigerant)  # Critical pressure (Pa)
            h_min = CP.PropsSI("H", "T", T_triple + 0.1, "Q", 0, self.refrigerant)
            T_max_K =  T_critical*0.9
            p_high = min(p_critical * 0.9, 30e5) 
            h_max = CP.PropsSI("H", "T", T_max_K, "P", p_high, self.refrigerant)
            self.nw_Heating_net._set_p_range([p_triple, p_high])
            self.nw_Heating_net._set_h_range([h_min,h_max])
            self.Heating_ude.params['dt'] = dt_DHN
            self.nw_Heating_net.solve('design')
    def interaction_simulation(self,dT_water):
        if self.mode=="COOLING_NET":
            self.net.heat_consumer.at[self.HC_ext_id, "qext_w"] =abs( self.Cooling_net_evaporator.Q.val)
            self.net.heat_consumer.at[self.HC_ext_id,"deltat_k"]=dT_water
            self.net.heat_consumer.at[self.HC_inj_id, "in_service"] =False
            
        elif self.mode=="HEATING_NET":
            self.net.heat_consumer.at[self.HC_inj_id, "qext_w"] = self.Heating_net_condenser.Q.val
            self.net.heat_consumer.at[self.HC_inj_id,"deltat_k"]=dT_water
            self.net.heat_consumer.at[self.HC_ext_id, "in_service"] =False

        else: 
            self.net.heat_consumer.at[self.HC_ext_id, "in_service"] =False
            self.net.heat_consumer.at[self.HC_inj_id, "in_service"] =False

    def get_main_results(self):
        if self.mode=="COOLING_NET":
            results = {
                "Q_consumer": abs(self.Cooling_net_condenser.Q.val),
                "Q_network": abs(self.Cooling_net_evaporator.Q.val),
                "W_compressor":self.Cooling_net_compressor.P.val ,
                "COP": abs(self.Cooling_net_condenser.Q.val)/self.Cooling_net_compressor.P.val 
            }
        elif self.mode=="HEATING_NET":
            results = {
                "Q_consumer": abs(self.Heating_net_evaporator.Q.val),
                "Q_network": abs(self.Heating_net_condenser.Q.val),
                "COP": abs(self.Heating_net_evaporator.Q.val)/self.Heating_net_compressor.P.val 
            }
        else:
            results = {}
        return results

    def get_results_solver(self):
        if self.mode=="COOLING_NET":
            self.nw_Cooling_net.print_results()
        elif self.mode=="HEATING_NET":
            self.nw_Heating_net.print_results()
        else:
            return None
net = pp.create_empty_network(fluid="water")
# Nudos de la Central / Fuente
j_fuente_ida = pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Fuente_Ida")
j_nodo_1 = pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="nodo_1_ida")
j_nodo_2=pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="nodo_2_ida") 
j_HP_1 = pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="HP_1_Ida")
j_HP_2 = pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="HP_2_Ida")
#Return
j_fuente_ret = pp.create_junction(net, pn_bar=1.5, tfluid_k=333.15, name="Fuente_Retorno")
j_nodo_1_ret = pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Node_1_ret")
j_nodo_2_ret=pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="Nodo_2_ret") 
j_HP_ret_1= pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="HP_1_ret")
j_HP_ret_2=pp.create_junction(net, pn_bar=5.0, tfluid_k=353.15, name="HP_2_ret")

#Plant-Nodo
u=0.35 / (np.pi * 0.15)
#Planta 1
pipe_ida_1 = pp.create_pipe_from_parameters(
    net, from_junction=j_fuente_ida, to_junction=j_nodo_1,
    length_km=0.0589, inner_diameter_mm=150, u_w_per_m2k=u, text_k=273.2, name="Tubo_Ida_Plant_Nodo_1",k_mm=0.1*1000
)

pipe_retorno_1= pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_1_ret, to_junction=j_fuente_ret,
    length_km=0.0589, inner_diameter_mm=150, u_w_per_m2k=u,  text_k=273.2, name="Tubo_RetornoPlant_Nodo_1",k_mm=0.1*1000)

#Nodo-nodo
pipe_ida_2 = pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_1, to_junction=j_nodo_2,
    length_km=0.0589, inner_diameter_mm=150, u_w_per_m2k=u,  text_k=273.2, name="nodo_1_nodo_2",k_mm=0.1*1000
)
pipe_retorno_2= pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_2_ret, to_junction=j_nodo_1_ret,
    length_km=0.0589, inner_diameter_mm=150, u_w_per_m2k=u,  text_k=273.2, name="nodo_2_ret_nodo_1_ret",k_mm=0.1*1000
)

#Node HP
#Node_Cons1

pipe_ida_3= pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_2, to_junction=j_HP_1,
    length_km=0.0376, inner_diameter_mm=150, u_w_per_m2k=u,  text_k=273.2, name="Tubo_Ida_nodo_2_cons_1_ida",k_mm=0.1*1000
)
pipe_retorno_3= pp.create_pipe_from_parameters(
    net, from_junction=j_HP_ret_1, to_junction=j_nodo_2_ret,
    length_km=0.0376, inner_diameter_mm=150, u_w_per_m2k=u,  text_k=273.2, name="Tubo_Retorno_nodo_2_cons_1_ret",k_mm=0.1*1000
)
#Node_Cons2
pipe_ida_4 = pp.create_pipe_from_parameters(
    net, from_junction=j_nodo_2, to_junction=j_HP_2,
    length_km=0.0302, inner_diameter_mm=150, u_w_per_m2k=u,  text_k=273.2, name="Tubo_Ida_nodo_2_cons_2_ida",k_mm=0.1*1000
)
pipe_retorno_4= pp.create_pipe_from_parameters(
    net, from_junction=j_HP_ret_2, to_junction=j_nodo_2_ret,
    length_km=0.0302, inner_diameter_mm=150, u_w_per_m2k=u,  text_k=273.2, name="Tubo_Retorno_nodo_2_cons_2_ret",k_mm=0.1*1000
)

#Heat Pumps
#Heat pump: extraction
HP_1_Ext=pp.create_heat_consumer(
    net,
    from_junction=j_HP_1 ,
    to_junction=j_HP_ret_1,
    qext_w=150000,
    deltat_k=50,
    name="HP_1_EXT"
)
#Heat mump 1: Injection
HP_1_inj=pp.create_heat_consumer(
    net,
    from_junction=j_HP_ret_1,
    to_junction=j_HP_1,
    qext_w=-150000,
    deltat_k=50,
    name="HP_1_INJ"
)
#Heat pump: extraction
HP_2_Ext=pp.create_heat_consumer(
    net,
    from_junction=j_HP_2 ,
    to_junction=j_HP_ret_2,
    qext_w=150000,
    deltat_k=50,
    name="HP_2_EXT"
)
#Heat mump 1: Injection
HP_2_inj=pp.create_heat_consumer(
    net,
    from_junction=j_HP_ret_2,
    to_junction=j_HP_2,
    qext_w=150000,
    deltat_k=-50,
    name="HP_2_INJ"
)
#Plant: 

Plant_1_ida = pp.create_ext_grid(
    net, junction=j_fuente_ida, p_bar=3.0,
    type="p", name="Grid_ida",in_service=False
)
Plant_1_ret = pp.create_ext_grid(
    net, junction=j_fuente_ret, p_bar=2.5,t_k=305,   # = p_flow_bar - plift_bar, para conservar el mismo salto de presión
    type="pt", name="Grid_ret",in_service=False
)
Plant_1=pp.create_circ_pump_const_pressure(net,flow_junction=j_fuente_ida,return_junction=j_fuente_ret,p_flow_bar=3,plift_bar=0.5,t_flow_k=340 ,name='Grid')
T_network_inital_guess_1=35
T_network_inital_guess_2=50
HP_1=Bidirectional_W_to_WHeatPump(name="heat_pump_1",refrigerant="R134a",net=net,HC_ext_id=HP_1_Ext,HC_inj_id=HP_1_inj)
HP_2=Bidirectional_W_to_WHeatPump(name="heat_pump_2",refrigerant="R134a",net=net,HC_ext_id=HP_2_Ext,HC_inj_id=HP_2_inj)
T_network_HP_1=T_network_inital_guess_1
T_network_HP_2=T_network_inital_guess_2
T_network_HP_1_loop=T_network_inital_guess_1
T_network_HP_2_loop=T_network_inital_guess_2
tolerance=1E-6
error_1=10
error_2=10
iterations=0
while error_1>tolerance or error_2>tolerance:
    HP_1.solve_cycle(mode="COOLING_NET",Q_consumer=-150,eta_s=0.95,T_nework_in=T_network_HP_1,T_cons=[50,60],dt_DHN=5)
    HP_2.solve_cycle(mode="HEATING_NET",Q_consumer=-150000,eta_s=0.95,T_nework_in=T_network_HP_2,T_cons=[35,25],dt_DHN=10)
    print("iteration")
    HP_1.interaction_simulation(dT_water=5)
    HP_2.interaction_simulation(dT_water=-10)
    try:
        pp.pipeflow(net,mode="bidirectional") 
    except UserWarning: 
        net.circ_pump_pressure.at[Plant_1, "in_service"] =False
        net.ext_grid.at[Plant_1_ida, "in_service"] =True
        net.ext_grid.at[Plant_1_ret, "in_service"] =True 
        pp.pipeflow(net,mode="bidirectional")
        net.circ_pump_pressure.at[Plant_1, "in_service"] =True
        net.ext_grid.at[Plant_1_ida, "in_service"] =False
        net.ext_grid.at[Plant_1_ret, "in_service"] =False
    T_network_HP_1=float(net.res_heat_consumer.at[HP_1.HC_ext_id,"t_from_k"]-273.15)
    T_network_HP_2=float(net.res_heat_consumer.at[HP_2.HC_inj_id,"t_from_k"]-273.15)
    error_1=abs(T_network_HP_1_loop-T_network_HP_1)
    error_2=abs(T_network_HP_2_loop-T_network_HP_2)
    print(error_1)
    print(error_2)
    T_network_HP_1_loop=T_network_HP_1
    T_network_HP_2_loop=T_network_HP_2
    iterations+=1

 iter  | residual   | progress   | massflow   | pressure   | enthalpy   | fluid      | energy     | component
-------+------------+------------+------------+------------+------------+------------+------------+------------
 1     | 9.08e+05   | 0 %        | 2.02e+00   | 1.42e+06   | 4.03e+05   | 0.00e+00   | 0.00e+00   | 0.00e+00
 2     | 4.56e+04   | 14 %       | 1.49e+00   | 1.97e+05   | 6.96e+03   | 0.00e+00   | 0.00e+00   | 0.00e+00
 3     | 7.04e+03   | 23 %       | 3.38e-01   | 1.64e+04   | 4.58e+02   | 0.00e+00   | 0.00e+00   | 0.00e+00
 4     | 1.73e+00   | 64 %       | 2.56e-06   | 1.58e+02   | 4.33e+00   | 0.00e+00   | 0.00e+00   | 0.00e+00
 5     | 1.70e-04   | 100 %      | 2.62e-12   | 1.41e-02   | 3.71e-04   | 0.00e+00   | 0.00e+00   | 0.00e+00
 6     | 3.45e-10   | 100 %      | 5.48e-15   | 4.94e-09   | 1.90e-08   | 0.00e+00   | 0.00e+00   | 0.00e+00
Total iterations: 6, Calculation time: 0.03 s, Iterations per second: 239.82

 iter  | residual   | progress   | massflow   | pressure   | enthalpy   | fluid      | energy     | component
-------+------------+------------+------------+------------+------------+------------+------------+------------
 1     | 4.52e+06   | 0 %        | 2.79e+00   | 1.61e+06   | 3.83e+05   | 0.00e+00   | 0.00e+00   | 0.00e+00
 2     | 5.44e+05   | 2 %        | 1.15e+00   | 2.95e+06   | 2.07e+06   | 0.00e+00   | 0.00e+00   | 0.00e+00
 3     | 1.92e+05   | 7 %        | 1.31e+02   | 5.76e+06   | 3.61e+05   | 0.00e+00   | 0.00e+00   | 0.00e+00
 4     | 3.90e+07   | 0 %        | 1.28e+03   | 2.11e+08   | 2.01e+06   | 0.00e+00   | 0.00e+00   | 0.00e+00
 5     | 4.43e+08   | 0 %        | 9.88e+04   | 2.17e+08   | 1.67e+06   | 0.00e+00   | 0.00e+00   | 0.00e+00
 6     | 1.00e+09   | 0 %        | 1.54e+05   | 4.04e+05   | 3.85e+05   | 0.00e+00   | 0.00e+00   | 0.00e+00
 7     | 2.42e+09   | 0 %        | 5.64e+04   | 5.97e+04   | 2.09e+03   | 0.00e+00   | 0.00e+00   | 0.00e+00
 8     | 8.87e+05   | 0 %        | 2.57e+01   | 2.70e+03   | 8.72e+01   | 0.00e+00   | 0.00e+00   | 0.00e+00
 9     | 6.50e+02   | 35 %       | 1.60e-02   | 4.85e+00   | 1.55e-01   | 0.00e+00   | 0.00e+00   | 0.00e+00
 10    | 8.17e-04   | 100 %      | 2.08e-08   | 1.56e-05   | 8.59e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
 11    | 2.61e-10   | 100 %      | 1.07e-12   | 1.00e-09   | 1.02e-08   | 0.00e+00   | 0.00e+00   | 0.00e+00
Total iterations: 11, Calculation time: 0.05 s, Iterations per second: 233.82
iteration
10.240118012803123
18.267219194168717

 iter  | residual   | progress   | massflow   | pressure   | enthalpy   | fluid      | energy     | component
-------+------------+------------+------------+------------+------------+------------+------------+------------
 1     | 2.58e+02   | 39 %       | 3.17e-04   | 2.03e+05   | 4.32e+04   | 0.00e+00   | 0.00e+00   | 0.00e+00
 2     | 3.50e+02   | 38 %       | 6.65e-04   | 2.18e+04   | 8.41e+02   | 0.00e+00   | 0.00e+00   | 0.00e+00
 3     | 7.34e+00   | 57 %       | 2.62e-07   | 3.94e+02   | 1.49e+01   | 0.00e+00   | 0.00e+00   | 0.00e+00
 4     | 2.22e-03   | 96 %       | 9.75e-11   | 1.22e-01   | 4.58e-03   | 0.00e+00   | 0.00e+00   | 0.00e+00
 5     | 5.07e-06   | 100 %      | 2.53e-14   | 1.24e-08   | 4.47e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
 6     | 2.92e-10   | 100 %      | 1.38e-14   | 8.86e-10   | 5.09e-08   | 0.00e+00   | 0.00e+00   | 0.00e+00
Total iterations: 6, Calculation time: 0.02 s, Iterations per second: 250.44

 iter  | residual   | progress   | massflow   | pressure   | enthalpy   | fluid      | energy     | component
-------+------------+------------+------------+------------+------------+------------+------------+------------
 1     | 3.35e+05   | 5 %        | 3.65e-01   | 7.94e+05   | 8.28e+04   | 0.00e+00   | 0.00e+00   | 0.00e+00
 2     | 2.27e+04   | 18 %       | 2.35e-01   | 1.13e+05   | 1.54e+03   | 0.00e+00   | 0.00e+00   | 0.00e+00
 3     | 2.69e+02   | 39 %       | 1.57e-03   | 4.41e+03   | 5.44e+01   | 0.00e+00   | 0.00e+00   | 0.00e+00
 4     | 2.91e-01   | 72 %       | 1.68e-06   | 6.05e+00   | 7.47e-02   | 0.00e+00   | 0.00e+00   | 0.00e+00
 5     | 1.24e-05   | 100 %      | 2.28e-12   | 1.15e-05   | 8.67e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
 6     | 1.13e-09   | 100 %      | 2.32e-10   | 4.00e-05   | 3.40e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
Total iterations: 6, Calculation time: 0.02 s, Iterations per second: 240.96
iteration
0.7750855324035797
0.0109733621895316

 iter  | residual   | progress   | massflow   | pressure   | enthalpy   | fluid      | energy     | component
-------+------------+------------+------------+------------+------------+------------+------------+------------
 1     | 1.84e+01   | 52 %       | 3.22e-05   | 1.21e+04   | 3.28e+03   | 0.00e+00   | 0.00e+00   | 0.00e+00
 2     | 2.13e+00   | 63 %       | 4.88e-06   | 1.14e+02   | 4.38e+00   | 0.00e+00   | 0.00e+00   | 0.00e+00
 3     | 2.01e-04   | 100 %      | 5.90e-11   | 1.05e-02   | 3.98e-04   | 0.00e+00   | 0.00e+00   | 0.00e+00
 4     | 3.43e-10   | 100 %      | 1.06e-14   | 8.70e-10   | 3.90e-08   | 0.00e+00   | 0.00e+00   | 0.00e+00
Total iterations: 4, Calculation time: 0.02 s, Iterations per second: 262.00

 iter  | residual   | progress   | massflow   | pressure   | enthalpy   | fluid      | energy     | component
-------+------------+------------+------------+------------+------------+------------+------------+------------
 1     | 1.83e+02   | 41 %       | 2.29e-04   | 3.42e+02   | 4.92e+01   | 0.00e+00   | 0.00e+00   | 0.00e+00
 2     | 1.06e-02   | 88 %       | 2.01e-07   | 3.60e-02   | 4.45e-04   | 0.00e+00   | 0.00e+00   | 0.00e+00
 3     | 9.93e-10   | 100 %      | 1.30e-11   | 2.00e-05   | 1.05e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
 4     | 7.65e-10   | 100 %      | 1.32e-11   | 2.00e-05   | 1.05e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
Total iterations: 4, Calculation time: 0.02 s, Iterations per second: 235.73
iteration
0.06265312293754732
4.266348832970834e-05

 iter  | residual   | progress   | massflow   | pressure   | enthalpy   | fluid      | energy     | component
-------+------------+------------+------------+------------+------------+------------+------------+------------
 1     | 1.48e+00   | 64 %       | 2.25e-06   | 9.59e+02   | 2.65e+02   | 0.00e+00   | 0.00e+00   | 0.00e+00
 2     | 1.40e-02   | 87 %       | 2.74e-08   | 7.39e-01   | 2.85e-02   | 0.00e+00   | 0.00e+00   | 0.00e+00
 3     | 4.58e-06   | 100 %      | 3.34e-13   | 4.41e-07   | 4.18e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
 4     | 5.62e-10   | 100 %      | 3.41e-13   | 4.60e-08   | 1.26e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
Total iterations: 4, Calculation time: 0.02 s, Iterations per second: 245.89

 iter  | residual   | progress   | massflow   | pressure   | enthalpy   | fluid      | energy     | component
-------+------------+------------+------------+------------+------------+------------+------------+------------
 1     | 7.13e-01   | 68 %       | 8.90e-07   | 1.33e+00   | 1.91e-01   | 0.00e+00   | 0.00e+00   | 0.00e+00
 2     | 1.26e-05   | 100 %      | 2.59e-10   | 5.47e-07   | 9.08e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
 3     | 3.36e-10   | 100 %      | 3.23e-12   | 0.00e+00   | 3.37e-08   | 0.00e+00   | 0.00e+00   | 0.00e+00
 4     | 1.08e-09   | 100 %      | 2.58e-10   | 0.00e+00   | 2.70e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
Total iterations: 4, Calculation time: 0.02 s, Iterations per second: 257.34
iteration
0.005094106567867129
4.017812557322031e-06

 iter  | residual   | progress   | massflow   | pressure   | enthalpy   | fluid      | energy     | component
-------+------------+------------+------------+------------+------------+------------+------------+------------
 1     | 1.21e-01   | 76 %       | 1.81e-07   | 7.78e+01   | 2.15e+01   | 0.00e+00   | 0.00e+00   | 0.00e+00
 2     | 9.72e-05   | 100 %      | 1.79e-10   | 4.88e-03   | 1.84e-04   | 0.00e+00   | 0.00e+00   | 0.00e+00
 3     | 4.71e-10   | 100 %      | 5.28e-15   | 2.47e-09   | 1.95e-08   | 0.00e+00   | 0.00e+00   | 0.00e+00
 4     | 2.94e-10   | 100 %      | 2.18e-14   | 1.99e-07   | 7.93e-08   | 0.00e+00   | 0.00e+00   | 0.00e+00
Total iterations: 4, Calculation time: 0.02 s, Iterations per second: 240.56

 iter  | residual   | progress   | massflow   | pressure   | enthalpy   | fluid      | energy     | component
-------+------------+------------+------------+------------+------------+------------+------------+------------
 1     | 6.71e-02   | 79 %       | 8.37e-08   | 1.25e-01   | 1.80e-02   | 0.00e+00   | 0.00e+00   | 0.00e+00
 2     | 1.26e-05   | 100 %      | 2.55e-10   | 5.66e-08   | 9.07e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
 3     | 1.04e-09   | 100 %      | 2.53e-10   | 4.60e-08   | 2.65e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
 4     | 9.50e-10   | 100 %      | 2.55e-10   | 1.11e-07   | 2.67e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
Total iterations: 4, Calculation time: 0.02 s, Iterations per second: 260.39
iteration
0.0004143818396187271
3.271965738349536e-07

 iter  | residual   | progress   | massflow   | pressure   | enthalpy   | fluid      | energy     | component
-------+------------+------------+------------+------------+------------+------------+------------+------------
 1     | 9.81e-03   | 88 %       | 1.47e-08   | 6.33e+00   | 1.75e+00   | 0.00e+00   | 0.00e+00   | 0.00e+00
 2     | 5.20e-06   | 100 %      | 1.19e-12   | 3.23e-05   | 2.81e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
 3     | 4.85e-10   | 100 %      | 2.44e-15   | 2.62e-09   | 9.05e-09   | 0.00e+00   | 0.00e+00   | 0.00e+00
 4     | 4.76e-10   | 100 %      | 2.62e-14   | 4.83e-23   | 9.70e-08   | 0.00e+00   | 0.00e+00   | 0.00e+00
Total iterations: 4, Calculation time: 0.02 s, Iterations per second: 224.33

 iter  | residual   | progress   | massflow   | pressure   | enthalpy   | fluid      | energy     | component
-------+------------+------------+------------+------------+------------+------------+------------+------------
 1     | 5.47e-03   | 91 %       | 6.72e-09   | 1.02e-02   | 1.47e-03   | 0.00e+00   | 0.00e+00   | 0.00e+00
 2     | 7.21e-10   | 100 %      | 1.15e-11   | 2.01e-05   | 1.06e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
 3     | 9.43e-10   | 100 %      | 2.52e-10   | 0.00e+00   | 2.64e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
 4     | 4.92e-10   | 100 %      | 2.86e-12   | 0.00e+00   | 2.99e-08   | 0.00e+00   | 0.00e+00   | 0.00e+00
Total iterations: 4, Calculation time: 0.01 s, Iterations per second: 269.60
iteration
3.3709333877141034e-05
2.6617613002599683e-08

 iter  | residual   | progress   | massflow   | pressure   | enthalpy   | fluid      | energy     | component
-------+------------+------------+------------+------------+------------+------------+------------+------------
 1     | 7.98e-04   | 100 %      | 1.19e-09   | 5.15e-01   | 1.42e-01   | 0.00e+00   | 0.00e+00   | 0.00e+00
 2     | 4.57e-06   | 100 %      | 4.86e-16   | 2.13e-07   | 4.00e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
 3     | 5.04e-10   | 100 %      | 1.19e-14   | 3.06e-07   | 4.31e-08   | 0.00e+00   | 0.00e+00   | 0.00e+00
 4     | 4.22e-10   | 100 %      | 1.77e-15   | 3.06e-07   | 1.25e-08   | 0.00e+00   | 0.00e+00   | 0.00e+00
Total iterations: 4, Calculation time: 0.02 s, Iterations per second: 256.68

 iter  | residual   | progress   | massflow   | pressure   | enthalpy   | fluid      | energy     | component
-------+------------+------------+------------+------------+------------+------------+------------+------------
 1     | 4.45e-04   | 100 %      | 6.62e-10   | 8.19e-04   | 1.18e-04   | 0.00e+00   | 0.00e+00   | 0.00e+00
 2     | 9.84e-10   | 100 %      | 2.55e-10   | 1.77e-09   | 2.67e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
 3     | 3.00e-10   | 100 %      | 1.58e-12   | 5.31e-09   | 1.66e-08   | 0.00e+00   | 0.00e+00   | 0.00e+00
 4     | 1.06e-09   | 100 %      | 2.54e-10   | 7.08e-09   | 2.66e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
Total iterations: 4, Calculation time: 0.02 s, Iterations per second: 243.25
iteration
2.742220658547012e-06
2.1651089809893165e-09

 iter  | residual   | progress   | massflow   | pressure   | enthalpy   | fluid      | energy     | component
-------+------------+------------+------------+------------+------------+------------+------------+------------
 1     | 6.49e-05   | 100 %      | 9.70e-11   | 4.19e-02   | 1.16e-02   | 0.00e+00   | 0.00e+00   | 0.00e+00
 2     | 3.24e-10   | 100 %      | 9.85e-15   | 5.02e-09   | 3.66e-08   | 0.00e+00   | 0.00e+00   | 0.00e+00
 3     | 4.67e-10   | 100 %      | 1.25e-14   | 2.47e-09   | 4.61e-08   | 0.00e+00   | 0.00e+00   | 0.00e+00
 4     | 3.27e-10   | 100 %      | 2.44e-14   | 0.00e+00   | 9.04e-08   | 0.00e+00   | 0.00e+00   | 0.00e+00
Total iterations: 4, Calculation time: 0.02 s, Iterations per second: 240.45

 iter  | residual   | progress   | massflow   | pressure   | enthalpy   | fluid      | energy     | component
-------+------------+------------+------------+------------+------------+------------+------------+------------
 1     | 3.63e-05   | 100 %      | 3.90e-11   | 6.80e-05   | 9.83e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
 2     | 2.81e-10   | 100 %      | 2.28e-12   | 6.73e-17   | 2.38e-08   | 0.00e+00   | 0.00e+00   | 0.00e+00
 3     | 1.15e-09   | 100 %      | 2.60e-10   | 1.56e-12   | 2.72e-06   | 0.00e+00   | 0.00e+00   | 0.00e+00
 4     | 6.94e-10   | 100 %      | 1.22e-12   | 0.00e+00   | 1.28e-08   | 0.00e+00   | 0.00e+00   | 0.00e+00
Total iterations: 4, Calculation time: 0.02 s, Iterations per second: 259.26
iteration
2.2306710434349952e-07
1.7621459846850485e-10

In [352]:
net.res_pipe

,v_mean_m_per_s,p_from_bar,p_to_bar,t_from_k,t_to_k,t_outlet_k,mdot_from_kg_per_s,mdot_to_kg_per_s,vdot_m3_per_s,reynolds,lambda,dp_friction_loss_bar
0,-0.227743,3.000000,3.045543,314.742677,314.794053,314.742677,-3.990387,3.990387,-0.004025,53522.886442,0.451064,-4.554290e-02
1,-0.226943,2.454592,2.500000,304.960722,305.000000,304.960722,-3.990387,3.990387,-0.004010,44154.838411,0.451318,-4.540826e-02
2,-0.227748,3.045543,3.091087,314.794053,314.845492,314.794053,-3.990387,3.990387,-0.004025,53572.497890,0.451063,-4.554374e-02
3,-0.226940,2.409184,2.454592,304.891903,304.960722,304.921492,-3.990387,3.990387,-0.004010,44119.618922,0.451319,-4.540780e-02
4,0.000322,3.091087,3.091086,314.845492,297.066598,297.066598,0.005654,-0.005654,0.000006,63.827438,1.452572,1.874093e-07
5,0.000320,2.409184,2.409184,292.066598,304.891903,284.024991,0.005654,-0.005654,0.000006,42.217508,1.965827,2.524600e-07
6,-0.228074,3.091087,3.114505,314.845492,314.871854,314.845492,-3.996041,3.996041,-0.004030,53686.058236,0.451060,-2.341826e-02
7,-0.227257,2.385836,2.409184,304.871854,304.891903,304.871854,-3.996041,3.996041,-0.004016,44129.019944,0.451318,-2.334765e-02